add ruby.exchange logo: faucet and desc
skalenetwork/skale-network pull request #149
Opened 2022-09-24 08:35 UTC by RubyAquaMarine

2022-09-27 17:28 UTC, cstrangedk approved these changes

2022-09-27 17:59 UTC, cstrangedk requested changes

2022-09-27 17:59 UTC, cstrangedk commented on metadata/mainnet/chains.json
> +    "faucet": "https://ruby.exchange/faucet.html",
faucet -> faucetUrl

2022-09-28 17:23 UTC, dmitry-tk approved these changes

2022-09-28 19:54 UTC, cstrangedk approved these changes

2022-09-28 19:55 UTC, merged