Add additional metadata
skalenetwork/skale-network pull request #189
Opened 2023-06-26 17:49 UTC by dmytrotkk

2023-06-26 17:56 UTC, payvint approved these changes

2023-06-26 18:19 UTC, TheGreatAxios requested changes

2023-06-26 18:19 UTC, TheGreatAxios commented on metadata/mainnet/chains.json
>    "potable-majestic-rasalhague": {
Remove this chain - no longer active

2023-06-26 18:20 UTC, TheGreatAxios requested changes

2023-06-26 18:20 UTC, TheGreatAxios commented on metadata/mainnet/chains.json
>    "potable-majestic-rasalhague": {
Remove this chain, no longer active

2023-06-26 18:56 UTC, SKALE-jace approved these changes

2023-06-26 19:02 UTC, payvint approved these changes

2023-06-26 19:02 UTC, dmytrotkk commented on metadata/mainnet/chains.json
>    "potable-majestic-rasalhague": {
removed

2023-06-27 00:37 UTC, TheGreatAxios requested changes
Please remove old chains

2023-06-27 00:37 UTC, TheGreatAxios commented on metadata/mainnet/chains.json
>    "snappy-quarrelsome-salm": {
Remove this chain, it is not active

2023-06-27 00:37 UTC, TheGreatAxios commented on metadata/mainnet/chains.json
Remove elegant-answer 
No longer live

Please remove the chain above and add Clet Domains to the honorable-steel-rasalhague chain

2023-06-27 00:37 UTC, TheGreatAxios commented on metadata/mainnet/chains.json
^ Line 89

2023-06-27 12:49 UTC, dmytrotkk commented on metadata/mainnet/chains.json
moved to Calypso 👍

2023-06-27 12:50 UTC, merged